### ISSUE TITLE
Add image optimizer to the repository

### ISSUE THREAD

**Issue by scriptswhisper** [manugentile/manugentile.github.io#2]
I think you can benefit from Imgbot to compress your images!

For more info check the [post](https://www.linkedin.com/posts/airscript_imgbot-github-opensource-activity-7109415771063095297-qOlO/) of @airscripts.

Imgbot: https://imgbot.net/

**Comment by manugentile** [comment]
thanks a lot @scriptswhisper, I've just added imgbot to this repo 🤩
