### ISSUE TITLE
Replace relative path with absolute path for images

### ISSUE THREAD

**Issue by scriptswhisper** [manugentile/manugentile.github.io#24]
I open this issue since I saw that moving files and refactoring gives some layout error because the markdown file location is changed.
Examples (now are OK):
- [Sql basics](https://github.com/manugentile/manugentile.github.io/blob/dcf14c7704a2a3e00b264747edc9d61f6cb9bc25/courses/sql/1_basics/sql-basics.md?plain=1#L9)
- [Sql joins](https://github.com/manugentile/manugentile.github.io/blob/dcf14c7704a2a3e00b264747edc9d61f6cb9bc25/courses/sql/4_joins/sql-joins.md?plain=1#L5)

While relative paths are generally recommended for maintainability, using absolute paths could potentially address the current issue we're facing. WDYT? If you like it I can open a PR.

**Comment by manugentile** [comment]
go for it @scriptswhisper
