### ISSUE TITLE
About me section

### ISSUE THREAD

**Issue by scriptswhisper** [manugentile/manugentile.github.io#26]
We need to add the about me section, but first @manugentile we need to define what you want to add.
 I suggest:
- actual role
- actual company (optional)
- socials (linkedin, github, website, etc)
- picture (optional)
- phrase/motto (optional)

**Comment by manugentile** [comment]
> We need to add the about me section, but first @manugentile we need to define what you want to add. I suggest:
> 
> * actual role

Agree

> * actual company (optional)

Agree

> * socials (linkedin, github, website, etc)

Agree

> * picture (optional)

Agree

> * phrase/motto (optional)

I really don't have one 🙈

**Comment by scriptswhisper** [comment]
Don't worry for the last point, I will make a draft pr. We can work together on this

**Comment by manugentile** [comment]
I've added the personal pic [here](https://github.com/manugentile/manugentile.github.io/blob/main/assets/img/mg_about.jpg)

**Comment by scriptswhisper** [comment]
Hi @manugentile , starting from your (feat/about) branch, I've make some changes. 
Let me know if you like it!
https://github.com/scriptswhisper/manugentile.github.io/tree/feat/about

**Comment by manugentile** [comment]
Absolutely yes!!
We now need to create the about readme and I was wondering to reduce the pic size, it seems sooo huge 🤔

**Comment by scriptswhisper** [comment]
Updated with 300x300 image
https://github.com/scriptswhisper/manugentile.github.io/tree/feat/about
