### ISSUE TITLE
Feat: add back button 

### ISSUE THREAD

**Issue by scriptswhisper** [manugentile/manugentile.github.io#36]
I think we can add a back button to each section or to the _main_ one like the followings:
- [command types](https://manugentile.github.io/courses/sql/2_command-types/)
- [basics](https://manugentile.github.io/courses/sql/1_basics/sql-basics.html)
- [operators](https://manugentile.github.io/courses/sql/3_operators/)

WDYT?

**Comment by manugentile** [comment]
I totally agree, gonna do that right now 😎
