### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by scriptswhisper** [manugentile/manugentile.github.io#51]
Hello,
I would suggest adding new topics to the repository to improve its reachability and help people discover it, for example:
- [Course](https://github.com/topics/course) with ~ 5k repo
- [Education](https://github.com/topics/education) with ~ 10k repo
- [Database](https://github.com/topics/database) with ~ 33k repo

WDYT?

**Comment by manugentile** [comment]
totally agree 😎
